services:
  proxy:
    build: ./proxy
    depends_on:
      - app
    ports:
      - 9002:6080
    command: --vnc app:5900
    networks:
      - x11

  app:
    build: ./app
    networks:
      - x11

networks:
  x11: